import { People } from '../people.interface';

export const people: Array<People> = [
  {
    id: '0148093543698',
    name: 'Ronaldo Nascimento Filho',
    birthdate: '1980-11-01T00:00:00-00:00',
    genre: 'male',
    city: '3550308',
    status: 'active',
    nickname: 'ronaldo.filho',
    email: 'ronaldo.nf@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: [
      {
        id: 109481,
        name: 'Maria',
        age: '10',
        related: 'Daughter',
        birthdate: '2008-12-10'
      },
      {
        id: 109482,
        name: 'Joana',
        age: '12',
        related: 'Daughter',
        birthdate: '2008-12-10'
      },
      {
        id: 109483,
        name: 'Pedro',
        age: '13',
        related: 'Son',
        birthdate: '2008-12-10'
      },
      {
        id: 109484,
        name: 'Paulo',
        age: '15',
        related: 'Son',
        birthdate: '2008-12-10'
      },
      {
        id: 109485,
        name: 'José',
        age: '19',
        related: 'Son',
        birthdate: '2008-12-10'
      }
    ]
  },
  {
    id: '0248093584089',
    name: 'Nivalda Oliveira',
    birthdate: '1997-01-21T00:00:00-00:00',
    genre: 'female',
    city: '4209102',
    status: 'active',
    nickname: 'nivalda.oliveira',
    email: 'nivalda.oliveira@bol.com.br',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Ativo',
    cityName: 'Joinville',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: []
  },
  {
    id: '0348093615904',
    name: 'Leonardo Silveira',
    birthdate: '1995-07-15T00:00:00-00:00',
    genre: 'male',
    city: '4209102',
    status: 'active',
    nickname: 'leo.silveira',
    email: 'leonardo.silveira@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'Joinville',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: []
  },
  {
    id: '0448093615904',
    name: 'Rafaela Gonçalvez Dias',
    birthdate: '1993-05-20T00:00:00-00:00',
    genre: 'female',
    city: '4215802',
    status: 'active',
    nickname: 'rafaelagdias',
    email: 'rafaelagdias@google.com.br',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Ativo',
    cityName: 'São Bento do Sul',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: []
  },
  {
    id: '0548093770300',
    name: 'Marcos Paulo Silva',
    birthdate: '1998-05-11T00:00:00-00:00',
    genre: 'other',
    city: '4209102',
    status: 'active',
    nickname: 'mpaulo.silva',
    email: 'mpaulo.silva@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Outros',
    statusDescription: 'Ativo',
    cityName: 'Joinville',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: []
  },
  {
    id: '0648093812893',
    name: 'João Severino',
    birthdate: '1995-10-07T00:00:00-00:00',
    genre: 'male',
    city: '4216206',
    status: 'active',
    nickname: 'jseverino',
    email: 'jseverino@yahoo.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'São Francisco do Sul',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: [
      {
        id: 109481,
        name: 'Maria',
        age: '10',
        related: 'Daughter',
        birthdate: '2008-12-10'
      }
    ]
  },
  {
    id: '0748093840433',
    name: 'José Marcos Cardoso',
    birthdate: '1986-08-01T00:00:00-00:00',
    genre: 'male',
    city: '4201307',
    status: 'inactive',
    nickname: 'jose',
    email: 'jose@outlook.com',
    nationality: 'Brazilian',
    birthPlace: '3550308',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Inativo',
    cityName: 'Araquari',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: [
      {
        id: 109483,
        name: 'Pedro',
        age: '13',
        related: 'Son',
        birthdate: '2008-12-10'
      },
      {
        id: 109484,
        name: 'Paulo',
        age: '15',
        related: 'Son',
        birthdate: '2008-12-10'
      },
      {
        id: 109485,
        name: 'José',
        age: '19',
        related: 'Son',
        birthdate: '2008-12-10'
      }
    ]
  },
  {
    id: '0848094890811',
    name: 'Karlo Rodrigues',
    birthdate: '1989-12-28T00:00:00-00:00',
    genre: 'male',
    city: '3550308',
    status: 'active',
    nickname: 'krodrigues',
    email: 'krodrigues@uol.com.br',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '0948094960731',
    name: 'Filipa Assunção',
    birthdate: '1985-02-18T00:00:00-00:00',
    genre: 'female',
    city: '3509502',
    status: 'active',
    nickname: 'filipaassuncao',
    email: 'filipaassuncao@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Ativo',
    cityName: 'Campinas',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1048094984943',
    name: 'Washington Camilo Domingues',
    birthdate: '1990-03-02T00:00:00-00:00',
    genre: 'male',
    city: '3534401',
    status: 'active',
    nickname: 'washington.domingues',
    email: 'washington.domingues@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'Osasco',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1148095011290',
    name: 'Alice Flores Gentil',
    birthdate: '1990-04-17T00:00:00-00:00',
    genre: 'female',
    city: '3550308',
    status: 'active',
    nickname: 'alice.gentil',
    email: 'alice.gentil@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: [
      {
        id: 109481,
        name: 'Maria',
        age: '10',
        related: 'Daughter',
        birthdate: '2008-12-10'
      }
    ]
  },
  {
    id: '1248095039078',
    name: 'Nilson Lacerda de Meireles',
    birthdate: '1989-01-10T00:00:00-00:00',
    genre: 'male',
    city: '3550308',
    status: 'active',
    nickname: 'nilsonlm',
    email: 'nilsonlm@outlook.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1348095069802',
    name: 'Flavio Menezes',
    birthdate: '1980-04-12T00:00:00-00:00',
    genre: 'male',
    city: '3550308',
    status: 'active',
    nickname: 'flavio.menezes',
    email: 'flavio.menezes@terra.com.br',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1448095103604',
    name: 'Jamir Oliveira Peixoto',
    birthdate: '1986-12-23T00:00:00-00:00',
    genre: 'other',
    city: '3550308',
    status: 'active',
    nickname: 'jamirpeixoto',
    email: 'jamirpeixoto@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Outros',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1548095119839',
    name: 'Mateus Padilha',
    birthdate: '1990-08-30T00:00:00-00:00',
    genre: 'male',
    city: '3550308',
    status: 'inactive',
    nickname: 'mateus.padilha',
    email: 'mateus.padilha@hotmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Inativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1648095136211',
    name: 'Leonardo Pinheiro da Silva',
    birthdate: '1990-08-25T00:00:00-00:00',
    genre: 'male',
    city: '3550308',
    status: 'active',
    nickname: 'leosilva',
    email: 'leosilva@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Papai',
    mother: 'Mamãe',
    street: 'Santos Dumont',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1748423226478',
    name: 'Benício Rafael Emanuel Melo',
    birthdate: '1997-11-09T00:00:00-00:00',
    genre: 'other',
    city: '3550308',
    status: 'active',
    nickname: 'bbeniciorafael',
    email: 'bbeniciorafael@bol.com.br',
    nationality: 'Brazilian',
    birthPlace: 'São Paulo',
    graduation: 'College',
    father: 'Anderson Samuel Henry Emanuel Melo',
    mother: 'Sarah Emanuelly Isabel',
    street: 'Quadra SQS 406 Bloco R',
    country: 'Brasil',
    genreDescription: 'Outros',
    statusDescription: 'Ativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1848423398317',
    name: 'Gabriela Evelyn Peixoto',
    birthdate: '1997-08-12T00:00:00-00:00',
    genre: 'female',
    city: '3550308',
    status: 'inactive',
    nickname: 'gabrielapeixoto',
    email: 'gabrielapeixoto_@gmail.com',
    nationality: 'Brazilian',
    birthPlace: '4209102',
    graduation: 'College',
    father: 'Geraldo Augusto Peixoto',
    mother: 'Ester Elza',
    street: 'Vila Primeiro de Outubro',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Inativo',
    cityName: 'São Paulo',
    state: 'São Paulo',
    uf: 'SP',
    dependents: []
  },
  {
    id: '1948423398317',
    name: 'Evelyn Tânia Isabelly Silveira',
    birthdate: '1994-09-23T00:00:00-00:00',
    genre: 'female',
    city: '3304557',
    status: 'active',
    nickname: 'evelyntis',
    email: 'evelyntis@gmail.com',
    nationality: 'Brazilian',
    birthPlace: '4209102',
    graduation: 'College',
    father: 'Enrico Lucca Silveira',
    mother: 'Carolina Mirella',
    street: 'Rua Delaide Benato Bieda',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Ativo',
    cityName: 'Rio de Janeiro',
    state: 'Rio de Janeiro',
    uf: 'RJ',
    dependents: []
  },
  {
    id: '2048423699851',
    name: 'Gael Isaac Pereira',
    birthdate: '1993-04-08T00:00:00-00:00',
    genre: 'male',
    city: '4106902',
    status: 'active',
    nickname: 'ggaelisaacpereira',
    email: 'ggaelisaacpereira@yahoo.com',
    nationality: 'Brazilian',
    birthPlace: 'Curitiba',
    graduation: 'College',
    father: 'Caleb Antonio Pereira',
    mother: 'Mariana Yasmin Márcia',
    street: 'Travessa Sabiá',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'Curitiba',
    state: 'Paraná',
    uf: 'PR',
    dependents: []
  },
  {
    id: '2148423866631',
    name: 'Theo Matheus Hugo Melo',
    birthdate: '1987-04-03T00:00:00-00:00',
    genre: 'other',
    city: '4106902',
    status: 'active',
    nickname: 'theomhmelo',
    email: 'theomhmelo@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'Curitiba',
    graduation: 'College',
    father: 'Thales Breno Martin Melo',
    mother: 'Natália Mirella',
    street: 'Rua Bom Jesus',
    country: 'Brasil',
    genreDescription: 'Outros',
    statusDescription: 'Ativo',
    cityName: 'Curitiba',
    state: 'Paraná',
    uf: 'PR',
    dependents: []
  },
  {
    id: '2248423892070',
    name: 'Otávio Murilo Oliveira',
    birthdate: '1994-12-10T00:00:00-00:00',
    genre: 'male',
    city: '4209102',
    status: 'active',
    nickname: 'otavio_oliveira',
    email: 'otavio_oliveira@gmail.com',
    nationality: 'Brazilian',
    birthPlace: 'Curitiba',
    graduation: 'College',
    father: 'Hugo Oliver Fernando Oliveira',
    mother: 'Lavínia Vera Oliveira',
    street: 'Avenida Bernardo Vieira de Melo',
    country: 'Brasil',
    genreDescription: 'Masculino',
    statusDescription: 'Ativo',
    cityName: 'Joinville',
    state: 'Santa Catarina',
    uf: 'SC',
    dependents: []
  },
  {
    id: '2348424005030',
    name: 'Valentina Aurora Assis',
    birthdate: '1994-07-24T00:00:00-00:00',
    genre: 'female',
    city: '1501402',
    status: 'active',
    nickname: 'vvalentinaauroraassis',
    email: 'vvalentinaauroraassis@terra.com.br',
    nationality: 'Brazilian',
    birthPlace: 'Belém',
    graduation: 'College',
    father: 'Iago César Assis',
    mother: 'Débora Sônia Assis',
    street: 'Passagem Brotinho',
    country: 'Brasil',
    genreDescription: 'Feminino',
    statusDescription: 'Ativo',
    cityName: 'Belém',
    state: 'Pará',
    uf: 'PA',
    dependents: []
  }
];
